_wandb:
    value:
        cli_version: 0.21.1
        e:
            z5d9yyf7m8mo17n1oqy7eisrb6zxhydw:
                args:
                    - --data_dir
                    - /data1/nwang60/datasets/CV-Dataset
                    - --use_wandb
                    - --channel_mode
                    - rgb_fft_grad
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1889085706240"
                        used: "1636722827264"
                email: ningsenw@gmail.com
                executable: /data1/nwang60/miniconda3/envs/medvlthinker/bin/python
                git:
                    commit: 1ad0a035a40947d665e5d48f725d8c062d16b731
                    remote: https://github.com/Wangningsen/FDU-2025CV-PJ.git
                gpu: NVIDIA RTX A5000
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-9afe49f0-6bc1-8576-d81f-1fa61b835935
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-8045de2b-c2cf-bd96-a792-987afda82ec7
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-cc23d5b7-b47e-cff1-1bdf-447a1c64d092
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-89b7fd75-9072-fe43-0c58-94d4081e74e0
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-1a2cdf14-33b6-6812-6b1a-a6a1682caeae
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-05c132eb-f9d9-7e9d-b7cf-3cb0e2c35588
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-2ededd68-fe3c-e0be-1aa4-65362d4a8616
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-58f79b25-4e45-3592-fe7d-a5b3bfd1465e
                host: vlaa-02
                memory:
                    total: "270298218496"
                os: Linux-6.8.0-51-generic-x86_64-with-glibc2.39
                program: /home/nwang60/FDU-2025CV-PJ/train.py
                python: CPython 3.10.18
                root: /home/nwang60/FDU-2025CV-PJ
                startedAt: "2025-12-10T10:46:51.245864Z"
                writerId: z5d9yyf7m8mo17n1oqy7eisrb6zxhydw
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 1
                - 2
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 32
channel_mode:
    value: rgb_fft_grad
data_dir:
    value: /data1/nwang60/datasets/CV-Dataset
epochs:
    value: 50
img_size:
    value: 256
lr:
    value: 0.001
num_workers:
    value: 4
save_dir:
    value: ./weights
seed:
    value: 42
use_wandb:
    value: true
val_ratio:
    value: 0.1
weight_decay:
    value: 0.0001
